/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_game_jqgame_ScoreManager */

#ifndef _Included_com_game_jqgame_ScoreManager
#define _Included_com_game_jqgame_ScoreManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_game_jqgame_ScoreManager_TOSCOREWALL
#define com_game_jqgame_ScoreManager_TOSCOREWALL 0L
#undef com_game_jqgame_ScoreManager_CONSUME
#define com_game_jqgame_ScoreManager_CONSUME 1L
/*
 * Class:     com_game_jqgame_ScoreManager
 * Method:    getScoreResult
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_coco_java
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
