/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_game_jqgame_ScoreManager */

#ifndef _Included_org_game_doudizhu_ZJSMS
#define _Included_org_game_doudizhu_ZJSMS
#ifdef __cplusplus
extern "C" {
#endif
#undef org_game_doudizhu_ScoreManager_TOSCOREWALL
#define org_game_doudizhu_ScoreManager_TOSCOREWALL 0L
#undef org_game_doudizhu_ScoreManager_CONSUME
#define org_game_doudizhu_ScoreManager_CONSUME 1L
/*
 * Class:     com_game_jqgame_ScoreManager
 * Method:    getScoreResult
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_game_doudizhu_ZJSMS_onSendMessageResult
  (JNIEnv *, jclass, jint type,jint code);

#ifdef __cplusplus
}
#endif
#endif
